# Generated by Django 4.1.1 on 2023-05-21 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='active',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
