# Generated by Django 4.1.1 on 2023-05-31 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_remove_applicant_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='email',
            field=models.CharField(default=None, max_length=64, null=True),
        ),
    ]
