# Generated by Django 4.2.1 on 2023-05-31 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_applicant_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='cv',
            field=models.FileField(blank=True, upload_to='media'),
        ),
    ]
