# Generated by Django 4.2.1 on 2023-05-31 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_applicant_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='cv',
            field=models.FileField(null=True, upload_to='media/'),
        ),
    ]
